apiVersion: v1
kind: Deployment
metadata:
  name: someapp
  namespace: someapp
spec:
  template:
    spec:
    - name: app
      volumeMounts:
      - name: config
        mountPath: /etc/config
    volumes:
      - name: config-volume
        configMap:
          name: someapp

