#!/bin/bash -e

if [ -z "${1}" ]; then
  echo "no file provided"
  exit 1
fi

function extract() {
  echo $(echo "${1}" | jq -r "${2}")
}

input="$(yq . ${1})"

metadata=$(extract "${input}" '.metadata')
name=$(extract "${metadata}" '.name')
namespace=$(extract "${metadata}" '.namespace')
vaultPath=$(extract "${input}" '.vaultPath')

secret="$(VAULT_ADDR=http://127.0.0.1:8200 vault kv get -format=json ${vaultPath})"
if [ $? -ne 0 ]; then
  echo "secret ${vaultPath} not found"
  exit 1
fi

secret=$(extract "${secret}" '.data.data' | jq -r '. | map_values(@base64)')
cat <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: $name
  namespace: $namespace
data: $secret
EOF
