apiVersion: v1
kind: Service
metadata:
  name: someapp
  namespace: someapp
  labels:
    app: someapp
spec:
  selector:
    app: someapp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
